apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversap-distancia
spec:
  replicas: 8
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
        - name: conversao-distancia
          image: danielcoelhocdk/conversao-distancia:v2
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: conversao-distancia
spec:
  selector:
    app: conversao-distancia
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31000
  type: NodePort
